//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Movies.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Movies.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Info.
        /// </summary>
        internal static string AddtionalInfoHeader {
            get {
                return ResourceManager.GetString("AddtionalInfoHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string BudgetLabel {
            get {
                return ResourceManager.GetString("BudgetLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cast.
        /// </summary>
        internal static string CastSubheader {
            get {
                return ResourceManager.GetString("CastSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification.
        /// </summary>
        internal static string CertificationLabel {
            get {
                return ResourceManager.GetString("CertificationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string ClearAction {
            get {
                return ResourceManager.GetString("ClearAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap for less.
        /// </summary>
        internal static string CollapseContentHint {
            get {
                return ResourceManager.GetString("CollapseContentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string CompaniesSubheader {
            get {
                return ResourceManager.GetString("CompaniesSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Companies.
        /// </summary>
        internal static string CompanyListEmptyView {
            get {
                return ResourceManager.GetString("CompanyListEmptyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Credits.
        /// </summary>
        internal static string CreditListEmptyView {
            get {
                return ResourceManager.GetString("CreditListEmptyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crew.
        /// </summary>
        internal static string CrewSubheader {
            get {
                return ResourceManager.GetString("CrewSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No description provided.
        /// </summary>
        internal static string DescriptionNull {
            get {
                return ResourceManager.GetString("DescriptionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string DoneAction {
            get {
                return ResourceManager.GetString("DoneAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No items!.
        /// </summary>
        internal static string EmptyItemListText {
            get {
                return ResourceManager.GetString("EmptyItemListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap for more.
        /// </summary>
        internal static string ExpandContentHint {
            get {
                return ResourceManager.GetString("ExpandContentHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore.
        /// </summary>
        internal static string ExploreTab {
            get {
                return ResourceManager.GetString("ExploreTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No additional filters.
        /// </summary>
        internal static string FiltersEmptyView {
            get {
                return ResourceManager.GetString("FiltersEmptyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        internal static string FindTab {
            get {
                return ResourceManager.GetString("FindTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string GenresLabel {
            get {
                return ResourceManager.GetString("GenresLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        internal static string KeywordsLabel {
            get {
                return ResourceManager.GetString("KeywordsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lists.
        /// </summary>
        internal static string ListsTab {
            get {
                return ResourceManager.GetString("ListsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movies.
        /// </summary>
        internal static string MoviesTab {
            get {
                return ResourceManager.GetString("MoviesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networks.
        /// </summary>
        internal static string NetworksSubheader {
            get {
                return ResourceManager.GetString("NetworksSubheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        internal static string OpenListButtonText {
            get {
                return ResourceManager.GetString("OpenListButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Language.
        /// </summary>
        internal static string OriginalLanguageLabel {
            get {
                return ResourceManager.GetString("OriginalLanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Title.
        /// </summary>
        internal static string OriginalTitleLabel {
            get {
                return ResourceManager.GetString("OriginalTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string PeopleHeader {
            get {
                return ResourceManager.GetString("PeopleHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        internal static string PeopleTab {
            get {
                return ResourceManager.GetString("PeopleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        internal static string PoweredByLabel {
            get {
                return ResourceManager.GetString("PoweredByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string ProductionHeader {
            get {
                return ResourceManager.GetString("ProductionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string RatingCountText {
            get {
                return ResourceManager.GetString("RatingCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No ratings available.
        /// </summary>
        internal static string RatingListEmptyView {
            get {
                return ResourceManager.GetString("RatingListEmptyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string RatingsHeader {
            get {
                return ResourceManager.GetString("RatingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string ReleaseLabel {
            get {
                return ResourceManager.GetString("ReleaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string RevenueLabel {
            get {
                return ResourceManager.GetString("RevenueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string ReviewsText {
            get {
                return ResourceManager.GetString("ReviewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime.
        /// </summary>
        internal static string RuntimeLabel {
            get {
                return ResourceManager.GetString("RuntimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Reviews.
        /// </summary>
        internal static string SeeReviewsText {
            get {
                return ResourceManager.GetString("SeeReviewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsToolbar {
            get {
                return ResourceManager.GetString("SettingsToolbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TV Shows.
        /// </summary>
        internal static string TVShowsTab {
            get {
                return ResourceManager.GetString("TVShowsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available to stream.
        /// </summary>
        internal static string WatchProvidersEmptyView {
            get {
                return ResourceManager.GetString("WatchProvidersEmptyView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where to Watch.
        /// </summary>
        internal static string WhereToWatchHeader {
            get {
                return ResourceManager.GetString("WhereToWatchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years Active.
        /// </summary>
        internal static string YearsActiveLabel {
            get {
                return ResourceManager.GetString("YearsActiveLabel", resourceCulture);
            }
        }
    }
}
