<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net10.0-android;net10.0-ios;net10.0</TargetFrameworks>
		<!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net8.0-tizen</TargetFrameworks> -->
		<OutputType Condition="'$(TargetFramework)' != 'net10.0'">Exe</OutputType>

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->
		
		<RootNamespace>Movies</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- Display name -->
		<ApplicationTitle>Movies</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.gml.movies</ApplicationId>

		<!-- Versions -->
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>
		
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">33.0</SupportedOSPlatformVersion>
		<NeutralLanguage>en-US</NeutralLanguage>
	</PropertyGroup>

	<PropertyGroup Condition="'$(TargetFramework)'=='net10.0-ios'">
	  <ProvisioningType>manual</ProvisioningType>
	  <CodesignKey>Apple Development: Created via API (UJYAVK5R6G)</CodesignKey>
	</PropertyGroup>

	<ItemGroup>
		<!-- App Icon -->
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />
		<MauiIcon Include="Resources\AppIcon\icon.png" />

		<!-- Splash Screen -->
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.png" Resize="True" BaseSize="300,185" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<None Remove="Resources\AppIcon\icon.png" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="Microsoft.Maui.Controls" Version="10.0.31" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="10.0.31" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\Code\C#\MauiExtensions\MauiExtensions.csproj" />
		<ProjectReference Include="..\..\..\Code\C#\System.Extensions\System.Extensions.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="AppShell.xaml.cs">
	    <DependentUpon>AppShell.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Strings\AppResources.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>AppResources.resx</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ItemListCompactView.xaml.cs">
	    <DependentUpon>ItemListCompactView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\DetailView.xaml.cs">
	    <DependentUpon>DetailView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ItemThumbnail\CollectionThumbnailView.xaml.cs">
	    <DependentUpon>CollectionThumbnailView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ItemThumbnail\CompanyThumbnailView.xaml.cs">
	    <DependentUpon>CompanyThumbnailView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ItemThumbnail\TVSeasonThumbnailView.xaml.cs">
	    <DependentUpon>TVSeasonThumbnailView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ItemThumbnail\MediaThumbnailView.xaml.cs">
	    <DependentUpon>MediaThumbnailView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ItemThumbnail\EpisodeThumbnailView.xaml.cs">
	    <DependentUpon>EpisodeThumbnailView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\Pages\MediaDetailPage.xaml.cs">
	    <DependentUpon>MediaDetailPage.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\ItemThumbnail\PersonThumbnailView.xaml.cs">
	    <DependentUpon>PersonThumbnailView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\QuickActionsPanel.xaml.cs">
	    <DependentUpon>QuickActionsPanel.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Views\FilterView.xaml.cs">
	    <DependentUpon>FilterView.xaml</DependentUpon>
	  </Compile>
	  <Compile Update="Resources\Templates\ListTemplate.xaml.cs">
	    <DependentUpon>ListTemplate.xaml</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resources\Strings\AppResources.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>AppResources.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
	  <MauiXaml Update="Filter\SelectableOptionsLayout.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\FilterResources.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\LightTheme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Styles\DarkTheme.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Resources\Templates\Templates.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ItemThumbnail\CollectionThumbnailView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ItemThumbnail\CompanyThumbnailView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ItemThumbnail\EpisodeThumbnailView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ItemThumbnail\MediaThumbnailView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ItemThumbnail\TVSeasonThumbnailView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ItemListCompactView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\FullCollectionView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Pages\MediaDetailPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Pages\ExplorePage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\Pages\ListsPage.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	  <MauiXaml Update="Views\ItemThumbnail\PersonThumbnailView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </MauiXaml>
	</ItemGroup>

	<ItemGroup>
	  <None Update="Views\CollectionDetailView.xaml">
	    <Generator>MSBuild:Compile</Generator>
	  </None>
	</ItemGroup>

</Project>
